### ISSUE TITLE
Automatically set up hosts file in docker-compose

### ISSUE THREAD

**Issue by Silic0nS0ldier** [userfrosting/UserFrosting#925]
Currently the docker configuration uses localhost with a specific port. Not the easiest thing to remember and port collisions can be a problem. Something like https://github.com/guillemcanal/docker-hostmanager may help here, and offer a way to support HTTPS locally.

**Comment by ssnukala** [comment]
http://blog.nbellocam.me/2016/03/01/nginx-serving-multiple-sites-docker/ here is another potential option. need to research this

**Comment by Silic0nS0ldier** [comment]
If we aren't able to find a "docker native" solution, we might be able to do something with https://www.npmjs.com/package/hostile

**Comment by Silic0nS0ldier** [comment]
Another alternative that I've stumbled onto is Traefik. It is quite extensible, well supported, and while experimenting with it locally no hosts needed to be set (I'd guess there is quite a bit behind the scenes). Provided its reliable enough, this would offer an excellent solution and potentially even play a role in #1003.

**Comment by ssnukala** [comment]
The following modifications to the docker-compose.yaml will achieve this
```
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    networks:
      - reverse-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  nginx:
    environment:
      VIRTUAL_HOST: usrefrosting.localhost
      VIRTUAL_PORT: 80
    restart: unless-stopped
    tty: true
    expose:
      - 8615
      - 8616
    ports:
      - 8615:80
      - 8616:443
    build:
      context: ./docker/nginx
    volumes:
      - .:/app
    depends_on:
      - app
      - mysqlprod
      - mysqltest
    networks:
      - reverse-proxy
      - backend
networks:
  backend:
  reverse-proxy:
```
This works, and you can now access the image with http://userfrosting.localhost. After you add this entry into your `hosts` file
